### ISSUE TITLE
[Bug]: EMMA senzors Unavailable on version 1.6.0 (works on 1.5.8)

### ISSUE THREAD

**Issue by poemihai** [wlcrs/huawei_solar#1150]
### Describe the issue

**Describe the issue**
All sensors of EMMA become Unavailable after updating to 1.6.0.
Inverter/Batteries reports corect data.
This issue isn't present if i revert to 1.5.8
Inverter has been added again using EMMA local IP.

**How do you connect to the inverter?**
Emma in SmartGuard through Modbus local network (using cable) - this method isn't listed below so i choose sdongle via cable - I DON't have a dongle since all are connected through EMMA.

### Describe your Huawei Solar Setup

Inverter Type: 1x SUN2000-5KTL-L1
Inverter Firmware version:  latest ***151
sDongle present:  No
sDongle Type: -
sDongle Connectivitiy: Ethernet
sDongle Firmware: -
Power meter present: built-in EMMA
Optimizers Present: No
Battery: 1x LUNA2000-S1 7kWh
Battery Firmware version: latest
Huawei Solar integration version: 1.6.0

### How do you connect to the inverter?

Via the SDongle, wired connection

### Upload your Diagnostics File

[config_entry-huawei_solar-01K7M9PKE315JTN4SCJ2QFKZ5M.json](https://github.com/user-attachments/files/22944886/config_entry-huawei_solar-01K7M9PKE315JTN4SCJ2QFKZ5M.json)

### Upload your relevant debug logs

```text
2025-10-16 11:18:30.554 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-10-16 11:18:30.556 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration google_home which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-10-16 11:18:30.556 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration huawei_solar which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-10-16 11:18:33.530 DEBUG (MainThread) [pymodbus.logging] Connecting to 192.168.1.186:502.
2025-10-16 11:18:33.530 DEBUG (MainThread) [pymodbus.logging] Connecting comm
2025-10-16 11:18:33.535 DEBUG (MainThread) [pymodbus.logging] Connected to comm
2025-10-16 11:18:33.538 DEBUG (MainThread) [huawei_solar.modbus] Waiting for 1500 milliseconds after connection before performing operations
2025-10-16 11:18:33.641 INFO (MainThread) [huawei_solar.huawei_solar] Waiting for connection
2025-10-16 11:18:35.040 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 30000 with length 15 from server 0
2025-10-16 11:18:35.040 DEBUG (MainThread) [pymodbus.logging] send: 0x0 0x1 0x0 0x0 0x0 0x6 0x0 0x3 0x75 0x30 0x0 0xf
2025-10-16 11:18:35.044 DEBUG (MainThread) [pymodbus.logging] recv: 0x0 0x1 0x0 0x0 0x0 0x21 0x0 0x3 0x1e 0x53 0x6d 0x61 0x72 0x74 0x48 0x45 0x4d 0x53 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 extra data: 
2025-10-16 11:18:35.044 DEBUG (MainThread) [pymodbus.logging] Processing: 0x0 0x1 0x0 0x0 0x0 0x21 0x0 0x3 0x1e 0x53 0x6d 0x61 0x72 0x74 0x48 0x45 0x4d 0x53 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0
2025-10-16 11:18:35.044 DEBUG (MainThread) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[21357, 24946, 29768, 17741, 21248, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], status=1, retries=0) 
2025-10-16 11:18:35.044 DEBUG (MainThread) [huawei_solar.huawei_solar] Sleeping for 0.049719 seconds before making next call
2025-10-16 11:18:35.097 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 30015 with length 50 from server 0
2025-10-16 11:18:35.097 DEBUG (MainThread) [pymodbus.logging] send: 0x0 0x2 0x0 0x0 0x0 0x6 0x0 0x3 0x75 0x3f 0x0 0x32
2025-10-16 11:18:35.101 DEBUG (MainThread) [pymodbus.logging] recv: 0x0 0x2 0x0 0x0 0x0 0x67 0x0 0x3 0x64 0x4e 0x53 0x32 0x35 0x36 0x31 0x32 0x34 0x39 0x37 0x31 0x39 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x53 0x6d 0x61 0x72 0x74 0x48 0x45 0x4d 0x53 0x20 0x56 0x31 0x30 0x30 0x52 0x30 0x32 0x34 0x43 0x31 0x30 0x53 0x50 0x43 0x31 0x31 0x31 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 extra data: 
2025-10-16 11:18:35.101 DEBUG (MainThread) [pymodbus.logging] Processing: 0x0 0x2 0x0 0x0 0x0 0x67 0x0 0x3 0x64 0x4e 0x53 0x32 0x35 0x36 0x31 0x32 0x34 0x39 0x37 0x31 0x39 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x53 0x6d 0x61 0x72 0x74 0x48 0x45 0x4d 0x53 0x20 0x56 0x31 0x30 0x30 0x52 0x30 0x32 0x34 0x43 0x31 0x30 0x53 0x50 0x43 0x31 0x31 0x31 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0
2025-10-16 11:18:35.101 DEBUG (MainThread) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[20051, 12853, 13873, 12852, 14647, 12601, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 21357, 24946, 29768, 17741, 21280, 22065, 12336, 21040, 12852, 17201, 12371, 20547, 12593, 12544, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], status=1, retries=0) 
2025-10-16 11:18:35.101 DEBUG (MainThread) [huawei_solar.huawei_solar] Sleeping for 0.049777 seconds before making next call
2025-10-16 11:18:35.153 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 30222 with length 20 from server 0
2025-10-16 11:18:35.153 DEBUG (MainThread) [pymodbus.logging] send: 0x0 0x3 0x0 0x0 0x0 0x6 0x0 0x3 0x76 0xe 0x0 0x14
2025-10-16 11:18:35.156 DEBUG (MainThread) [pymodbus.logging] recv: 0x0 0x3 0x0 0x0 0x0 0x2b 0x0 0x3 0x28 0x45 0x4d 0x4d 0x41 0x2d 0x41 0x30 0x32 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 extra data: 
2025-10-16 11:18:35.156 DEBUG (MainThread) [pymodbus.logging] Processing: 0x0 0x3 0x0 0x0 0x0 0x2b 0x0 0x3 0x28 0x45 0x4d 0x4d 0x41 0x2d 0x41 0x30 0x32 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0
2025-10-16 11:18:35.156 DEBUG (MainThread) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[17741, 19777, 11585, 12338, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], status=1, retries=0) 
2025-10-16 11:18:35.157 DEBUG (MainThread) [huawei_solar.huawei_solar] Sleeping for 0.049367 seconds before making next call
2025-10-16 11:18:35.207 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 30000 with length 15 from server 4
2025-10-16 11:18:35.207 DEBUG (MainThread) [pymodbus.logging] send: 0x0 0x4 0x0 0x0 0x0 0x6 0x4 0x3 0x75 0x30 0x0 0xf
2025-10-16 11:18:35.210 DEBUG (MainThread) [pymodbus.logging] recv: 0x0 0x4 0x0 0x0 0x0 0x21 0x4 0x3 0x1e 0x53 0x55 0x4e 0x32 0x30 0x30 0x30 0x2d 0x35 0x4b 0x54 0x4c 0x2d 0x4c 0x31 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 extra data: 
2025-10-16 11:18:35.211 DEBUG (MainThread) [pymodbus.logging] Processing: 0x0 0x4 0x0 0x0 0x0 0x21 0x4 0x3 0x1e 0x53 0x55 0x4e 0x32 0x30 0x30 0x30 0x2d 0x35 0x4b 0x54 0x4c 0x2d 0x4c 0x31 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0
2025-10-16 11:18:35.211 DEBUG (MainThread) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[21333, 20018, 12336, 12333, 13643, 21580, 11596, 12544, 0, 0, 0, 0, 0, 0, 0], status=1, retries=0) 
2025-10-16 11:18:35.211 DEBUG (MainThread) [huawei_solar.huawei_solar] Sleeping for 0.049761 seconds before making next call
2025-10-16 11:18:35.261 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 30015 with length 50 from server 4
2025-10-16 11:18:35.262 DEBUG (MainThread) [pymodbus.logging] send: 0x0 0x5 0x0 0x0 0x0 0x6 0x4 0x3 0x75 0x3f 0x0 0x32
2025-10-16 11:18:35.265 DEBUG (MainThread) [pymodbus.logging] recv: 0x0 0x5 0x0 0x0 0x0 0x67 0x4 0x3 0x64 0x54 0x41 0x32 0x32 0x37 0x30 0x33 0x35 0x34 0x38 0x31 0x36 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x30 0x31 0x30 0x37 0x35 0x33 0x34 0x36 0x2d 0x30 0x31 0x35 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x56 0x32 0x30 0x30 0x52 0x30 0x30 0x31 0x43 0x30 0x30 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x56 0x32 0x30 0x30 0x52 0x30 0x30 0x31 0x43 0x30 0x30 0x53 0x50 0x43 0x31 0x35 0x31 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 extra data: 
2025-10-16 11:18:35.265 DEBUG (MainThread) [pymodbus.logging] Processing: 0x0 0x5 0x0 0x0 0x0 0x67 0x4 0x3 0x64 0x54 0x41 0x32 0x32 0x37 0x30 0x33 0x35 0x34 0x38 0x31 0x36 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x30 0x31 0x30 0x37 0x35 0x33 0x34 0x36 0x2d 0x30 0x31 0x35 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x56 0x32 0x30 0x30 0x52 0x30 0x30 0x31 0x43 0x30 0x30 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x56 0x32 0x30 0x30 0x52 0x30 0x30 0x31 0x43 0x30 0x30 0x53 0x50 0x43 0x31 0x35 0x31 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0
2025-10-16 11:18:35.265 DEBUG (MainThread) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[21569, 12850, 14128, 13109, 13368, 12598, 0, 0, 0, 0, 12337, 12343, 13619, 13366, 11568, 12597, 0, 0, 0, 0, 22066, 12336, 21040, 12337, 17200, 12288, 0, 0, 0, 0, 0, 0, 0, 0, 0, 22066, 12336, 21040, 12337, 17200, 12371, 20547, 12597, 12544, 0, 0, 0, 0, 0, 0], status=1, retries=0) 
2025-10-16 11:18:35.265 DEBUG (MainThread) [huawei_solar.huawei_solar] Sleeping for 0.049761 seconds before making next call
2025-10-16 11:18:35.316 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 30071 with length 1 from server 4
2025-10-16 11:18:35.316 DEBUG (MainThread) [pymodbus.logging] send: 0x0 0x6 0x0 0x0 0x0 0x6 0x4 0x3 0x75 0x77 0x0 0x1
2025-10-16 11:18:35.321 DEBUG (MainThread) [pymodbus.logging] recv: 0x0 0x6 0x0 0x0 0x0 0x5 0x4 0x3 0x2 0x0 0x2 extra data: 
2025-10-16 11:18:35.322 DEBUG (MainThread) [pymodbus.logging] Processing: 0x0 0x6 0x0 0x0 0x0 0x5 0x4 0x3 0x2 0x0 0x2
2025-10-16 11:18:35.322 DEBUG (MainThread) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[2], status=1, retries=0) 
2025-10-16 11:18:35.322 DEBUG (MainThread) [huawei_solar.huawei_solar] Sleeping for 0.049773 seconds before making next call
2025-10-16 11:18:35.373 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 37200 with length 1 from server 4
2025-10-16 11:18:35.373 DEBUG (MainThread) [pymodbus.logging] send: 0x0 0x7 0x0 0x0 0x0 0x6 0x4 0x3 0x91 0x50 0x0 0x1
2025-10-16 11:18:35.377 DEBUG (MainThread) [pymodbus.logging] recv: 0x0 0x7 0x0 0x0 0x0 0x5 0x4 0x3 0x2 0x0 0x0 extra data: 
2025-10-16 11:18:35.377 DEBUG (MainThread) [pymodbus.logging] Processing: 0x0 0x7 0x0 0x0 0x0 0x5 0x4 0x3 0x2 0x0 0x0
2025-10-16 11:18:35.377 DEBUG (MainThread) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[0], status=1, retries=0) 
2025-10-16 11:18:35.377 DEBUG (MainThread) [huawei_solar.huawei_solar] Sleeping for 0.049783 seconds before making next call
2025-10-16 11:18:35.427 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 47000 with length 1 from server 4
2025-10-16 11:18:35.428 DEBUG (MainThread) [pymodbus.logging] send: 0x0 0x8 0x0 0x0 0x0 0x6 0x4 0x3 0xb7 0x98 0x0 0x1
2025-10-16 11:18:35.431 DEBUG (MainThread) [pymodbus.logging] recv: 0x0 0x8 0x0 0x0 0x0 0x5 0x4 0x3 0x2 0x0 0x0 extra data: 
2025-10-16 11:18:35.431 DEBUG (MainThread) [pymodbus.logging] Processing: 0x0 0x8 0x0 0x0 0x0 0x5 0x4 0x3 0x2 0x0 0x0
2025-10-16 11:18:35.431 DEBUG (MainThread) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[0], status=1, retries=0) 
2025-10-16 11:18:35.432 DEBUG (MainThread) [huawei_solar.huawei_solar] Sleeping for 0.049717 seconds before making next call
2025-10-16 11:18:35.482 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 47089 with length 1 from server 4
2025-10-16 11:18:35.483 DEBUG (MainThread) [pymodbus.logging] send: 0x0 0x9 0x0 0x0 0x0 0x6 0x4 0x3 0xb7 0xf1 0x0 0x1
2025-10-16 11:18:35.486 DEBUG (MainThread) [pymodbus.logging] recv: 0x0 0x9 0x0 0x0 0x0 0x5 0x4 0x3 0x2 0x0 0x2 extra data: 
2025-10-16 11:18:35.486 DEBUG (MainThread) [pymodbus.logging] Processing: 0x0 0x9 0x0 0x0 0x0 0x5 0x4 0x3 0x2 0x0 0x2
2025-10-16 11:18:35.486 DEBUG (MainThread) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[2], status=1, retries=0) 
2025-10-16 11:18:35.486 DEBUG (MainThread) [huawei_solar.huawei_solar] Sleeping for 0.049729 seconds before making next call
2025-10-16 11:18:35.537 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 47954 with length 1 from server 4
2025-10-16 11:18:35.537 DEBUG (MainThread) [pymodbus.logging] send: 0x0 0xa 0x0 0x0 0x0 0x6 0x4 0x3 0xbb 0x52 0x0 0x1
2025-10-16 11:18:35.542 DEBUG (MainThread) [pymodbus.logging] recv: 0x0 0xa 0x0 0x0 0x0 0x3 0x4 0x83 0x3 extra data: 
2025-10-16 11:18:35.542 DEBUG (MainThread) [pymodbus.logging] Processing: 0x0 0xa 0x0 0x0 0x0 0x3 0x4 0x83 0x3
2025-10-16 11:18:35.542 DEBUG (MainThread) [huawei_solar.bridge] Storage capacity control as it is not supported by device 4
2025-10-16 11:18:35.542 DEBUG (MainThread) [huawei_solar.huawei_solar] Sleeping for 0.049691 seconds before making next call
2025-10-16 11:18:35.593 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 37100 with length 1 from server 4
2025-10-16 11:18:35.593 DEBUG (MainThread) [pymodbus.logging] send: 0x0 0xb 0x0 0x0 0x0 0x6 0x4 0x3 0x90 0xec 0x0 0x1
2025-10-16 11:18:35.597 DEBUG (MainThread) [pymodbus.logging] recv: 0x0 0xb 0x0 0x0 0x0 0x3 0x4 0x83 0x3 extra data: 
2025-10-16 11:18:35.597 DEBUG (MainThread) [pymodbus.logging] Processing: 0x0 0xb 0x0 0x0 0x0 0x3 0x4 0x83 0x3
2025-10-16 11:18:35.597 DEBUG (MainThread) [huawei_solar.huawei_solar] Sleeping for 0.049779 seconds before making next call
2025-10-16 11:18:35.648 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 42900 with length 1 from server 4
2025-10-16 11:18:35.648 DEBUG (MainThread) [pymodbus.logging] send: 0x0 0xc 0x0 0x0 0x0 0x6 0x4 0x3 0xa7 0x94 0x0 0x1
2025-10-16 11:18:35.651 DEBUG (MainThread) [pymodbus.logging] recv: 0x0 0xc 0x0 0x0 0x0 0x5 0x4 0x3 0x2 0x0 0x0 extra data: 
2025-10-16 11:18:35.651 DEBUG (MainThread) [pymodbus.logging] Processing: 0x0 0xc 0x0 0x0 0x0 0x5 0x4 0x3 0x2 0x0 0x0
2025-10-16 11:18:35.651 DEBUG (MainThread) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[0], status=1, retries=0) 
2025-10-16 11:18:35.652 DEBUG (MainThread) [huawei_solar.huawei_solar] Sleeping for 0.049705 seconds before making next call
2025-10-16 11:18:35.703 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 43006 with length 1 from server 4
2025-10-16 11:18:35.703 DEBUG (MainThread) [pymodbus.logging] send: 0x0 0xd 0x0 0x0 0x0 0x6 0x4 0x3 0xa7 0xfe 0x0 0x1
2025-10-16 11:18:35.706 DEBUG (MainThread) [pymodbus.logging] recv: 0x0 0xd 0x0 0x0 0x0 0x5 0x4 0x3 0x2 0x1 0xe0 extra data: 
2025-10-16 11:18:35.706 DEBUG (MainThread) [pymodbus.logging] Processing: 0x0 0xd 0x0 0x0 0x0 0x5 0x4 0x3 0x2 0x1 0xe0
2025-10-16 11:18:35.706 DEBUG (MainThread) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[480], status=1, retries=0) 
2025-10-16 11:18:35.744 INFO (MainThread) [custom_components.huawei_solar.number] Skipping number setup, as parameter configuration is not enabled
2025-10-16 11:18:35.746 INFO (MainThread) [custom_components.huawei_solar.select] Skipping select setup, as parameter configuration is not enabled
2025-10-16 11:18:35.748 DEBUG (MainThread) [custom_components.huawei_solar] Finished fetching NS2561249719_inverter_data_update_coordinator data in 0.000 seconds (success: True)
2025-10-16 11:18:35.759 ERROR (MainThread) [homeassistant.components.sensor] huawei_solar: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 807, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1314, in async_device_update
    await self.async_update()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 613, in async_update
    await self.coordinator.async_request_refresh()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'async_request_refresh'
2025-10-16 11:18:35.762 DEBUG (MainThread) [custom_components.huawei_solar] Finished fetching TA2270354816_inverter_data_update_coordinator data in 0.000 seconds (success: True)
2025-10-16 11:18:35.770 DEBUG (MainThread) [custom_components.huawei_solar] Finished fetching TA2270354816_battery_data_update_coordinator data in 0.000 seconds (success: True)
2025-10-16 11:18:35.776 INFO (MainThread) [custom_components.huawei_solar.switch] Skipping switch setup, as parameter configuration is not enabled
2025-10-16 11:18:35.900 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({% set meter_power = states('sensor.emma_feed_in_power') | float %}
        {% set inverter_power = states('sensor.inverter_active_power') | float %}
        {{ (inverter_power - meter_power )  | float(0) }}) renders=2>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template/__init__.py", line 2065, in forgiving_float_filter
    return float(value)
ValueError: could not convert string to float: 'unknown'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template/__init__.py", line 494, in async_render
    render_result = render_with_context(self.template, compiled, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template/context.py", line 45, in render_with_context
    return template.render(**kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/src/homeassistant/homeassistant/helpers/template/__init__.py", line 2068, in forgiving_float_filter
    raise_no_default("float", value)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template/helpers.py", line 13, in raise_no_default
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Template error: float got invalid input 'unknown' when rendering template '{% set meter_power = states('sensor.emma_feed_in_power') | float %}
        {% set inverter_power = states('sensor.inverter_active_power') | float %}
        {{ (inverter_power - meter_power )  | float(0) }}' but no default was specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template/__init__.py", line 611, in async_render_to_info
    render_info._result = self.async_render(  # noqa: SLF001
                          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
        variables, strict=strict, log_fn=log_fn, **kwargs
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/template/__init__.py", line 496, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: float got invalid input 'unknown' when rendering template '{% set meter_power = states('sensor.emma_feed_in_power') | float %}
        {% set inverter_power = states('sensor.inverter_active_power') | float %}
        {{ (inverter_power - meter_power )  | float(0) }}' but no default was specified
2025-10-16 11:18:35.904 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('ValueError: Template error: float got invalid input 'unknown' when rendering template '{% set meter_power = states('sensor.emma_feed_in_power') | float %}
        {% set inverter_power = states('sensor.inverter_active_power') | float %}
        {{ (inverter_power - meter_power )  | float(0) }}' but no default was specified') while processing template 'Template<template=({% set meter_power = states('sensor.emma_feed_in_power') | float %}
        {% set inverter_power = states('sensor.inverter_active_power') | float %}
        {{ (inverter_power - meter_power )  | float(0) }}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.consum_casa'
2025-10-16 11:18:35.905 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({% set meter_power = states('sensor.consum_casa') | float %}
        {% set inverter_power = states('sensor.inverter_input_power') | float %}
        {{ (inverter_power - meter_power )  | float(0) }}) renders=2>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template/__init__.py", line 2065, in forgiving_float_filter
    return float(value)
ValueError: could not convert string to float: 'unavailable'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template/__init__.py", line 494, in async_render
    render_result = render_with_context(self.template, compiled, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template/context.py", line 45, in render_with_context
    return template.render(**kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/src/homeassistant/homeassistant/helpers/template/__init__.py", line 2068, in forgiving_float_filter
    raise_no_default("float", value)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template/helpers.py", line 13, in raise_no_default
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Template error: float got invalid input 'unavailable' when rendering template '{% set meter_power = states('sensor.consum_casa') | float %}
        {% set inverter_power = states('sensor.inverter_input_power') | float %}
        {{ (inverter_power - meter_power )  | float(0) }}' but no default was specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template/__init__.py", line 611, in async_render_to_info
    render_info._result = self.async_render(  # noqa: SLF001
                          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
        variables, strict=strict, log_fn=log_fn, **kwargs
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/template/__init__.py", line 496, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: float got invalid input 'unavailable' when rendering template '{% set meter_power = states('sensor.consum_casa') | float %}
        {% set inverter_power = states('sensor.inverter_input_power') | float %}
        {{ (inverter_power - meter_power )  | float(0) }}' but no default was specified
2025-10-16 11:18:35.908 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('ValueError: Template error: float got invalid input 'unavailable' when rendering template '{% set meter_power = states('sensor.consum_casa') | float %}
        {% set inverter_power = states('sensor.inverter_input_power') | float %}
        {{ (inverter_power - meter_power )  | float(0) }}' but no default was specified') while processing template 'Template<template=({% set meter_power = states('sensor.consum_casa') | float %}
        {% set inverter_power = states('sensor.inverter_input_power') | float %}
        {{ (inverter_power - meter_power )  | float(0) }}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.injectie_retea'
2025-10-16 11:18:46.201 DEBUG (MainThread) [huawei_solar.bridge] Batch update of the following registers: inverter_total_absorbed_energy, energy_charged_today, total_charged_energy, energy_discharged_today, total_discharged_energy, consumption_today, feed_in_to_grid_today, total_feed_in_to_grid, supply_from_grid_today, total_supply_from_grid, inverter_energy_yield_today, inverter_total_energy_yield, pv_yield_today, total_pv_energy_yield, pv_output_power, load_power, feed_in_power, battery_charge_discharge_power, inverter_active_power
2025-10-16 11:18:46.201 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 30302 with length 64 from server 0
2025-10-16 11:18:46.201 DEBUG (MainThread) [pymodbus.logging] send: 0x0 0xe 0x0 0x0 0x0 0x6 0x0 0x3 0x76 0x5e 0x0 0x40
2025-10-16 11:18:46.206 DEBUG (MainThread) [pymodbus.logging] recv: 0x0 0xe 0x0 0x0 0x0 0x83 0x0 0x3 0x80 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x25 0x0 0x0 0x0 0x24 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x39 0x0 0x0 0x0 0xd 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0xbe 0x0 0x0 0x15 0x90 0x0 0x0 0x15 0x90 0x0 0x0 0x1a 0xf4 0x0 0x0 0x1 0x35 0x0 0x0 0x0 0x0 0x0 0x10 0x10 0x29 0x0 0x0 0x0 0x3 0x0 0x0 0x0 0x0 0x0 0x0 0x3 0x4f 0x0 0x0 0x1 0x6 0x0 0x0 0x0 0x0 0x0 0x0 0x5 0xbc 0x0 0x0 0x0 0x4a 0x0 0x10 0xd 0xe1 0x0 0x0 0x0 0x5e 0x0 0x0 0x0 0x0 0x0 0x10 0x9a 0xc6 0x0 0x0 0x1a 0xf4 0x0 0x0 0x0 0x4d 0x0 0x0 0x1 0xa8 0x0 0x0 0x0 0x12 0xff 0xff 0xfe 0xb7 0x0 0x0 0x13 0x88 0x0 0x0 0x1 0x96 extra data: 
2025-10-16 11:18:46.206 DEBUG (MainThread) [pymodbus.logging] Processing: 0x0 0xe 0x0 0x0 0x0 0x83 0x0 0x3 0x80 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x25 0x0 0x0 0x0 0x24 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x39 0x0 0x0 0x0 0xd 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0xbe 0x0 0x0 0x15 0x90 0x0 0x0 0x15 0x90 0x0 0x0 0x1a 0xf4 0x0 0x0 0x1 0x35 0x0 0x0 0x0 0x0 0x0 0x10 0x10 0x29 0x0 0x0 0x0 0x3 0x0 0x0 0x0 0x0 0x0 0x0 0x3 0x4f 0x0 0x0 0x1 0x6 0x0 0x0 0x0 0x0 0x0 0x0 0x5 0xbc 0x0 0x0 0x0 0x4a 0x0 0x10 0xd 0xe1 0x0 0x0 0x0 0x5e 0x0 0x0 0x0 0x0 0x0 0x10 0x9a 0xc6 0x0 0x0 0x1a 0xf4 0x0 0x0 0x0 0x4d 0x0 0x0 0x1 0xa8 0x0 0x0 0x0 0x12 0xff 0xff 0xfe 0xb7 0x0 0x0 0x13 0x88 0x0 0x0 0x1 0x96
2025-10-16 11:18:46.206 DEBUG (MainThread) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[0, 0, 0, 37, 0, 36, 0, 0, 0, 57, 0, 13, 0, 0, 0, 190, 0, 5520, 0, 5520, 0, 6900, 0, 309, 0, 0, 16, 4137, 0, 3, 0, 0, 0, 847, 0, 262, 0, 0, 0, 1468, 0, 74, 16, 3553, 0, 94, 0, 0, 16, 39622, 0, 6900, 0, 77, 0, 424, 0, 18, 65535, 65207, 0, 5000, 0, 406], status=1, retries=0) 
2025-10-16 11:18:46.207 DEBUG (MainThread) [huawei_solar.bridge] Batch update of the following registers: state_of_capacity
2025-10-16 11:18:46.207 DEBUG (MainThread) [huawei_solar.huawei_solar] Sleeping for 0.049268 seconds before making next call
2025-10-16 11:18:46.257 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 30368 with length 1 from server 0
2025-10-16 11:18:46.258 DEBUG (MainThread) [pymodbus.logging] send: 0x0 0xf 0x0 0x0 0x0 0x6 0x0 0x3 0x76 0xa0 0x0 0x1
2025-10-16 11:18:46.261 DEBUG (MainThread) [pymodbus.logging] recv: 0x0 0xf 0x0 0x0 0x0 0x5 0x0 0x3 0x2 0x8 0x98 extra data: 
2025-10-16 11:18:46.261 DEBUG (MainThread) [pymodbus.logging] Processing: 0x0 0xf 0x0 0x0 0x0 0x5 0x0 0x3 0x2 0x8 0x98
2025-10-16 11:18:46.261 DEBUG (MainThread) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[2200], status=1, retries=0) 
2025-10-16 11:18:46.261 DEBUG (MainThread) [huawei_solar.bridge] Batch update of the following registers: charger_temperature_sensor
2025-10-16 11:18:46.261 DEBUG (MainThread) [huawei_solar.huawei_solar] Sleeping for 0.049721 seconds before making next call
2025-10-16 11:18:46.311 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 30508 with length 2 from server 0
2025-10-16 11:18:46.312 DEBUG (MainThread) [pymodbus.logging] send: 0x0 0x10 0x0 0x0 0x0 0x6 0x0 0x3 0x77 0x2c 0x0 0x2
2025-10-16 11:18:46.316 DEBUG (MainThread) [pymodbus.logging] recv: 0x0 0x10 0x0 0x0 0x0 0x3 0x0 0x83 0x3 extra data: 
2025-10-16 11:18:46.316 DEBUG (MainThread) [pymodbus.logging] Processing: 0x0 0x10 0x0 0x0 0x0 0x3 0x0 0x83 0x3
2025-10-16 11:18:46.316 ERROR (MainThread) [custom_components.huawei_solar] Error fetching NS2561249719_inverter_data_update_coordinator data: Could not update NS2561249719 values: Got error while reading from register 30508 with length 2: ExceptionResponse(dev_id=0, function_code=131, exception_code=3)
2025-10-16 11:18:46.316 DEBUG (MainThread) [custom_components.huawei_solar] Finished fetching NS2561249719_inverter_data_update_coordinator data in 0.116 seconds (success: False)
2025-10-16 11:18:46.318 DEBUG (MainThread) [huawei_solar.bridge] Batch update of the following registers: state_1, state_2, state_3, alarm_1, alarm_2, alarm_3, pv_01_voltage, pv_01_current, pv_02_voltage, pv_02_current
2025-10-16 11:18:46.320 DEBUG (MainThread) [huawei_solar.huawei_solar] Sleeping for 0.046309 seconds before making next call
2025-10-16 11:18:46.366 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 32000 with length 20 from server 4
2025-10-16 11:18:46.367 DEBUG (MainThread) [pymodbus.logging] send: 0x0 0x11 0x0 0x0 0x0 0x6 0x4 0x3 0x7d 0x0 0x0 0x14
2025-10-16 11:18:46.370 DEBUG (MainThread) [pymodbus.logging] recv: 0x0 0x11 0x0 0x0 0x0 0x2b 0x4 0x3 0x28 0x0 0x6 0x0 0x0 0x0 0x7 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0xa8 0x78 0x9 0xd3 0x0 0x37 0x9 0x46 0x0 0x3e extra data: 
2025-10-16 11:18:46.370 DEBUG (MainThread) [pymodbus.logging] Processing: 0x0 0x11 0x0 0x0 0x0 0x2b 0x4 0x3 0x28 0x0 0x6 0x0 0x0 0x0 0x7 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0xa8 0x78 0x9 0xd3 0x0 0x37 0x9 0x46 0x0 0x3e
2025-10-16 11:18:46.370 DEBUG (MainThread) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[6, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 43128, 2515, 55, 2374, 62], status=1, retries=0) 
2025-10-16 11:18:46.370 DEBUG (MainThread) [huawei_solar.bridge] Batch update of the following registers: input_power, line_voltage_A_B, line_voltage_B_C, line_voltage_C_A, day_active_power_peak, active_power, reactive_power, power_factor, efficiency, internal_temperature, device_status, startup_time, shutdown_time, accumulated_yield_energy, total_dc_input_power, hourly_yield_energy, daily_yield_energy, monthly_yield_energy, yearly_yield_energy
2025-10-16 11:18:46.371 DEBUG (MainThread) [huawei_solar.huawei_solar] Sleeping for 0.049473 seconds before making next call
2025-10-16 11:18:46.421 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 32064 with length 56 from server 4
2025-10-16 11:18:46.421 DEBUG (MainThread) [pymodbus.logging] send: 0x0 0x12 0x0 0x0 0x0 0x6 0x4 0x3 0x7d 0x40 0x0 0x38
2025-10-16 11:18:46.425 DEBUG (MainThread) [pymodbus.logging] recv: 0x0 0x12 0x0 0x0 0x0 0x73 0x4 0x3 0x70 0x0 0x0 0x0 0x4d 0x9 0xd 0x0 0x0 0x0 0x0 0x4 0x80 0x0 0x0 0x0 0x0 0x0 0x0 0x7 0x19 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0xf 0x7f 0x0 0x0 0x1 0x96 0xff 0xff 0xff 0xff 0x3 0xe8 0x13 0x89 0x27 0x10 0x0 0xc9 0xb 0xb8 0x2 0x0 0x0 0x0 0x68 0xf0 0xb7 0x7e 0xff 0xff 0xff 0xff 0x0 0x0 0x1 0x97 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x25 0x0 0x10 0xd 0xe1 0x0 0x10 0x9a 0xc6 0x68 0xf0 0xd4 0x8f 0x0 0x0 0x0 0x9 0x0 0x0 0x0 0x4a 0x0 0x0 0x31 0x9d 0x0 0x7 0xf0 0x74 extra data: 
2025-10-16 11:18:46.425 DEBUG (MainThread) [pymodbus.logging] Processing: 0x0 0x12 0x0 0x0 0x0 0x73 0x4 0x3 0x70 0x0 0x0 0x0 0x4d 0x9 0xd 0x0 0x0 0x0 0x0 0x4 0x80 0x0 0x0 0x0 0x0 0x0 0x0 0x7 0x19 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0xf 0x7f 0x0 0x0 0x1 0x96 0xff 0xff 0xff 0xff 0x3 0xe8 0x13 0x89 0x27 0x10 0x0 0xc9 0xb 0xb8 0x2 0x0 0x0 0x0 0x68 0xf0 0xb7 0x7e 0xff 0xff 0xff 0xff 0x0 0x0 0x1 0x97 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x25 0x0 0x10 0xd 0xe1 0x0 0x10 0x9a 0xc6 0x68 0xf0 0xd4 0x8f 0x0 0x0 0x0 0x9 0x0 0x0 0x0 0x4a 0x0 0x0 0x31 0x9d 0x0 0x7 0xf0 0x74
2025-10-16 11:18:46.425 DEBUG (MainThread) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[0, 77, 2317, 0, 0, 1152, 0, 0, 0, 1817, 0, 0, 0, 0, 0, 3967, 0, 406, 65535, 65535, 1000, 5001, 10000, 201, 3000, 512, 0, 26864, 46974, 65535, 65535, 0, 407, 0, 0, 0, 0, 0, 0, 0, 0, 37, 16, 3553, 16, 39622, 26864, 54415, 0, 9, 0, 74, 0, 12701, 7, 61556], status=1, retries=0) 
2025-10-16 11:18:46.425 DEBUG (MainThread) [huawei_solar.bridge] Detected a device state change from None to On-grid : resetting power meter online status
2025-10-16 11:18:46.425 DEBUG (MainThread) [custom_components.huawei_solar] Finished fetching TA2270354816_inverter_data_update_coordinator data in 0.211 seconds (success: True)
2025-10-16 11:18:46.427 DEBUG (MainThread) [huawei_solar.bridge] Batch update of the following registers: storage_maximum_charge_power, storage_maximum_discharge_power
2025-10-16 11:18:46.427 DEBUG (MainThread) [huawei_solar.huawei_solar] Sleeping for 0.047676 seconds before making next call
2025-10-16 11:18:46.476 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 37046 with length 4 from server 4
2025-10-16 11:18:46.476 DEBUG (MainThread) [pymodbus.logging] send: 0x0 0x13 0x0 0x0 0x0 0x6 0x4 0x3 0x90 0xb6 0x0 0x4
2025-10-16 11:18:46.479 DEBUG (MainThread) [pymodbus.logging] recv: 0x0 0x13 0x0 0x0 0x0 0xb 0x4 0x3 0x8 0x0 0x0 0xd 0xac 0x0 0x0 0xd 0xac extra data: 
2025-10-16 11:18:46.479 DEBUG (MainThread) [pymodbus.logging] Processing: 0x0 0x13 0x0 0x0 0x0 0xb 0x4 0x3 0x8 0x0 0x0 0xd 0xac 0x0 0x0 0xd 0xac
2025-10-16 11:18:46.479 DEBUG (MainThread) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[0, 3500, 0, 3500], status=1, retries=0) 
2025-10-16 11:18:46.480 DEBUG (MainThread) [huawei_solar.bridge] Batch update of the following registers: storage_rated_capacity, storage_state_of_capacity, storage_running_status, storage_bus_voltage, storage_bus_current, storage_charge_discharge_power, storage_total_charge, storage_total_discharge, storage_current_day_charge_capacity, storage_current_day_discharge_capacity
2025-10-16 11:18:46.480 DEBUG (MainThread) [huawei_solar.huawei_solar] Sleeping for 0.049715 seconds before making next call
2025-10-16 11:18:46.530 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 37758 with length 30 from server 4
2025-10-16 11:18:46.531 DEBUG (MainThread) [pymodbus.logging] send: 0x0 0x14 0x0 0x0 0x0 0x6 0x4 0x3 0x93 0x7e 0x0 0x1e
2025-10-16 11:18:46.534 DEBUG (MainThread) [pymodbus.logging] recv: 0x0 0x14 0x0 0x0 0x0 0x3f 0x4 0x3 0x3c 0x0 0x0 0x1a 0xf4 0x0 0xdc 0x0 0x0 0x0 0x2 0x11 0xb2 0x0 0x7 0xff 0xff 0xfe 0xbb 0x0 0x0 0x1a 0xf4 0x0 0x0 0x1a 0xf4 0x0 0x0 0x15 0x90 0x0 0x0 0x15 0x90 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x39 0x0 0x0 0x0 0xbe 0x0 0x0 0x0 0x24 0x0 0x0 0x0 0xd extra data: 
2025-10-16 11:18:46.534 DEBUG (MainThread) [pymodbus.logging] Processing: 0x0 0x14 0x0 0x0 0x0 0x3f 0x4 0x3 0x3c 0x0 0x0 0x1a 0xf4 0x0 0xdc 0x0 0x0 0x0 0x2 0x11 0xb2 0x0 0x7 0xff 0xff 0xfe 0xbb 0x0 0x0 0x1a 0xf4 0x0 0x0 0x1a 0xf4 0x0 0x0 0x15 0x90 0x0 0x0 0x15 0x90 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x39 0x0 0x0 0x0 0xbe 0x0 0x0 0x0 0x24 0x0 0x0 0x0 0xd
2025-10-16 11:18:46.534 DEBUG (MainThread) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[0, 6900, 220, 0, 2, 4530, 7, 65535, 65211, 0, 6900, 0, 6900, 0, 5520, 0, 5520, 0, 0, 0, 0, 0, 0, 57, 0, 190, 0, 36, 0, 13], status=1, retries=0) 
2025-10-16 11:18:46.534 DEBUG (MainThread) [custom_components.huawei_solar] Finished fetching TA2270354816_battery_data_update_coordinator data in 0.312 seconds (success: True)
```

### Please confirm the following:

- [x] I'm running the latest release of Home Assistant.
- [x] I'm running the latest release of this integration.
- [x] I did not find an existing issue describing this problem.
- [x] I did upload the diagnostics-file that I could retrieve from  the 'Devices & Services Page'
- [x] I did upload the relevant debug logs (via 'Enable Debug Logging'-feature or by manually configuring HA logging)

**Comment by poemihai** [comment]
And an offtopic question: Is there a way to make a distinction between all disabled sensors of Voltage, Power, Energy soo i know what it is exactly? Also Temperature from EMMA it seems it doesn't work in 1.5.8 either (just noticed).

**Comment by wlcrs** [comment]
The integration fails to read the "external power meter voltage a-b" sensor of your EMMA. Do you have such an external power meter connected to your EMMA? Does that sensor work as expected in 1.5.8? 

Can you please upload a diagnostics file + logs with that version so that I can compare the behavior?

**Comment by poemihai** [comment]
I had an external power metter but it was removed since Emma does the control now. It was removed from plant too, also i remove old connection in Huawei Solar and added it again using Emma IP. 

That A-B voltage i get it using inverter senzors and is showing data corectly

These are the logs on 1.5.8 that is working prety much ok (only Emma temperature remains Unavailable - sensor.emma_temperature).

[config_entry-huawei_solar-01K7M9PKE315JTN4SCJ2QFKZ5M.json](https://github.com/user-attachments/files/22946416/config_entry-huawei_solar-01K7M9PKE315JTN4SCJ2QFKZ5M.json)
[home-assistant_huawei_solar_2025-10-16T10-12-38.437Z.log](https://github.com/user-attachments/files/22946415/home-assistant_huawei_solar_2025-10-16T10-12-38.437Z.log)

**Comment by wlcrs** [comment]
I overlooked that the CHARGER_TEMPERATURE_SENSOR has the same address as the EMMA_EXTERNAL_METER_LINE_VOLTAGE_A_B . 

Please disable the EMMA temperature sensor. It has already been removed from the EMMA sensor list in https://github.com/wlcrs/huawei_solar/commit/65bb6a17de6b87b0241a5fb64db0d6fd4701b90c (not released yet), as it refers to the temperature of the charger instead of the EMMA. 

Before doing the next release:
* [x] Check why the failure of one read operation suddenly fails the entire batch_update function.
* [x] Double check if all new EMMA/charger entities have a translation attached to them, which doesn't seem to be the case because of your second question.

**Comment by poemihai** [comment]
That did the trick. Now 1.6.0 works as expected (with emma temperature disabled).
Thank you for your time!

**Comment by fsteiger77** [comment]
Hi, i have the Same Problem... with 1.5.8 all will working after Update to 1.6 there is no Data from Emme but i can See the Information from the Batterie and from the Inverter and the Wallbox

[home-assistant_huawei_solar_2025-10-16T17-59-23.247Z.log](https://github.com/user-attachments/files/22956273/home-assistant_huawei_solar_2025-10-16T17-59-23.247Z.log)
[config_entry-huawei_solar-01K7GNE1NQRKZ6ENMY62X83VD3.json](https://github.com/user-attachments/files/22956274/config_entry-huawei_solar-01K7GNE1NQRKZ6ENMY62X83VD3.json)

**Comment by poemihai** [comment]
> Hi, i have the Same Problem... with 1.5.8 all will working after Update to 1.6 there is no Data from Emme but i can See the Information from the Batterie and from the Inverter and the Wallbox
> 
> [home-assistant_huawei_solar_2025-10-16T17-59-23.247Z.log](https://github.com/user-attachments/files/22956273/home-assistant_huawei_solar_2025-10-16T17-59-23.247Z.log) [config_entry-huawei_solar-01K7GNE1NQRKZ6ENMY62X83VD3.json](https://github.com/user-attachments/files/22956274/config_entry-huawei_solar-01K7GNE1NQRKZ6ENMY62X83VD3.json)

I would check to see if there is any Unavailable sensor on version 1.5.8 and if there is disable it after updating to 1.6.0 - this should fix it if it's something like my case.

**Comment by fsteiger77** [comment]
> > Hi, i have the Same Problem... with 1.5.8 all will working after Update to 1.6 there is no Data from Emme but i can See the Information from the Batterie and from the Inverter and the Wallbox
> > [home-assistant_huawei_solar_2025-10-16T17-59-23.247Z.log](https://github.com/user-attachments/files/22956273/home-assistant_huawei_solar_2025-10-16T17-59-23.247Z.log) [config_entry-huawei_solar-01K7GNE1NQRKZ6ENMY62X83VD3.json](https://github.com/user-attachments/files/22956274/config_entry-huawei_solar-01K7GNE1NQRKZ6ENMY62X83VD3.json)
> 
> I would check to see if there is any Unavailable sensor on version 1.5.8 and if there is disable it after updating to 1.6.0 - this should fix it if it's something like my case.

Hi, thanks i have all Entities disabled an one by one the status set to active now it works.

**Comment by bkuehnel795** [comment]
[config_entry-huawei_solar-01JVHTQ80YMSKN2KSRZW9RKS2E.json](https://github.com/user-attachments/files/22990012/config_entry-huawei_solar-01JVHTQ80YMSKN2KSRZW9RKS2E.json)

Hi, I still cant fix Emma in 1.6.0
I do get all the battery sensors, but Emma goes to unavailable complettly.
EMMA temp sensor ist deleted

Can you please tell, what you need to check the issue?

**Comment by wlcrs** [comment]
Closing as the todo's have been addressed in the v2.0 of this integration which has been released as an alpha version.
